version: '2'

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - nextcloud_network
  db:
    image: postgres
    restart: always
    volumes:
      - ./deployment/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: yourpassword
    networks:
      - nextcloud_network

  app:
    image: nextcloud
    ports:
      - 80:80
    links:
      - db
      - redis
    volumes:
      - ./deployment/nextcloud:/var/www/html
      - "./deployment/redis-session.ini:/usr/local/etc/php/conf.d/redis-session.
i
ni"
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: yourpassword
      NEXTCLOUD_ADMIN_USER: ${ADMIN_USERNAME}
      NEXTCLOUD_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: localhost ${ip4}
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
    driver: bridge
